services:
  nodecast-tv:
    image: ghcr.io/lkadar2015/nodecast-tv:latest
    build: https://github.com/lkadar2015/nodecast-tv-lkadar2015.git#main
    container_name: nodecast-tv
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    devices:
      - /dev/dri:/dev/dri # Required for VAAPI/QuickSync/AMF (Linux)
    group_add:       # Optional: Needed mainly if you run as non-root
      - "video"      # Run on host: getent group video
      - "render"     # Run on host: getent group render
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000 # Internal container port
